"""empty message

Revision ID: 400719177b09
Revises: 6903c0ae8ba0
Create Date: 2022-12-18 01:59:39.393727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400719177b09'
down_revision = '6903c0ae8ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_photos')
    # ### end Alembic commands ###
