"""empty message

Revision ID: b7a845c9ab0a
Revises: 400719177b09
Create Date: 2022-12-18 03:03:55.298926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a845c9ab0a'
down_revision = '400719177b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
